algoritmo "ExemploFormatação"


var
// Seção de Declaração de Variáveis
   a, b : real
   c : real
   x, y : real
   z : real

inicio
// Entrada de dados - valores já atribuídos
   a <- 12.5
   b <- 3.3
   c <- 2
   
   escreval(a:5:1)
   escreval(b:5:1)
   escreval(c:5:1)
   
   x <- 20.0
   y <- 5.5
   z <- 1.5
   
   escreval(x:5:1)
   escreval(y:5:1)
   escreval(z:5:1)

   //1º número: espaço; 2º número: casas decimais

fimalgoritmo